# Generated by Django 3.1.4 on 2021-03-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('stcatid', models.AutoField(primary_key=True, serialize=False)),
                ('stcatnm', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
