# Generated by Django 3.1.4 on 2021-03-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('stsubcatid', models.AutoField(primary_key=True, serialize=False)),
                ('stcatnm', models.CharField(max_length=50)),
                ('stsubcatnm', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
