# Generated by Django 3.1.4 on 2021-03-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='stsubcatnm',
            new_name='city',
        ),
    ]
