# Generated by Django 3.1.4 on 2021-03-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('catnm', models.CharField(max_length=50)),
                ('subcatnm', models.CharField(max_length=50)),
                ('baseprice', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('file1', models.CharField(max_length=100)),
                ('file2', models.CharField(max_length=100)),
                ('file3', models.CharField(max_length=100)),
                ('file4', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=100)),
                ('bstatus', models.IntegerField()),
                ('dt', models.CharField(max_length=1000)),
            ],
        ),
    ]
