# Generated by Django 3.1.4 on 2021-03-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0002_auto_20210307_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('mobile', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=200)),
                ('dt', models.CharField(max_length=200)),
            ],
        ),
    ]
