# Generated by Django 3.1.4 on 2021-03-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='stcatnm',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
